### ISSUE TITLE
Move `docs` to gitbook repo

### ISSUE THREAD

**Issue by lxsameer** [Yellowen/Faalis#114]
Move the `docs` and all the guides to gitbook repo.

**Comment by sadmad** [comment]
chetory? agha in getway error mide yebar zadam docker-compose up -d  dorost
shod.

**Comment by sadmad** [comment]
Hallo,

ich habe gerade die Petition „HBO: Remake Game of Thrones Season 8 with
competent writers." unterschrieben und wollte dich fragen, ob du auch
mitmachst.

Unser Ziel ist es, 1.000.000 Unterschriften zu sammeln und dafür brauchen
wir Unterstützung. Hier kannst du mehr über die Petition erfahren:

http://chng.it/RkZJD7LNvS

Vielen Dank!
sarmad
