### ISSUE TITLE
Runtime error undefined method `models_with_permission=' 

### ISSUE THREAD

**Issue by edelwies** [Yellowen/Faalis#54]
```
bundle exec rails server
warning: parser/current is loading parser/ruby22, which recognizes
warning: 2.2.3-compliant syntax, but you are running 2.2.1.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
=> Booting WEBrick
=> Rails 4.2.1 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Exiting
/home/mary/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/railtie.rb:196:in `method_missing': undefined method `models_with_permission=' for Faalis::Engine:Class (NoMethodError)
	from /home/mary/src/lovely_choices/config/initializers/faalis.rb:9:in `block in <top (required)>'
	from /home/mary/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/bundler/gems/Faalis-d250a3f0bfe6/lib/faalis/engine.rb:70:in `setup'
	from /home/mary/src/lovely_choices/config/initializers/faalis.rb:1:in `<top (required)>'
	from /home/mary/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
	from /home/mary/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `block in load'
	from /home/mary/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/mary/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
	from /home/mary/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/engine.rb:652:in `block in load_config_initializer'
	from /home/mary/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications.rb:166:in `instrument'
	from /home/mary/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/engine.rb:651:in `load_config_initializer'
	from /home/mary/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
	from /home/mary/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/engine.rb:615:in `each'
	from /home/mary/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/engine.rb:615:in `block in <class:Engine>'
	from /home/mary/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `instance_exec'
	from /home/mary/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `run'
	from /home/mary/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /home/mary/.rbenv/versions/2.2.1/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
	from /home/mary/.rbenv/versions/2.2.1/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /home/mary/.rbenv/versions/2.2.1/lib/ruby/2.2.0/tsort.rb:420:in `block (2 levels) in each_strongly_connected_component_from'
	from /home/mary/.rbenv/versions/2.2.1/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
	from /home/mary/.rbenv/versions/2.2.1/lib/ruby/2.2.0/tsort.rb:419:in `block in each_strongly_connected_component_from'
	from /home/mary/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/initializable.rb:44:in `each'
	from /home/mary/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/initializable.rb:44:in `tsort_each_child'
	from /home/mary/.rbenv/versions/2.2.1/lib/ruby/2.2.0/tsort.rb:413:in `call'
	from /home/mary/.rbenv/versions/2.2.1/lib/ruby/2.2.0/tsort.rb:413:in `each_strongly_connected_component_from'
	from /home/mary/.rbenv/versions/2.2.1/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /home/mary/.rbenv/versions/2.2.1/lib/ruby/2.2.0/tsort.rb:345:in `each'
	from /home/mary/.rbenv/versions/2.2.1/lib/ruby/2.2.0/tsort.rb:345:in `call'
	from /home/mary/.rbenv/versions/2.2.1/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
	from /home/mary/.rbenv/versions/2.2.1/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
	from /home/mary/.rbenv/versions/2.2.1/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
	from /home/mary/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/initializable.rb:54:in `run_initializers'
	from /home/mary/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/application.rb:352:in `initialize!'
	from /home/mary/src/lovely_choices/config/environment.rb:5:in `<top (required)>'
	from /home/mary/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
	from /home/mary/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/mary/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/mary/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
	from /home/mary/src/lovely_choices/config.ru:3:in `block in <main>'
	from /home/mary/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
	from /home/mary/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
	from /home/mary/src/lovely_choices/config.ru:in `new'
	from /home/mary/src/lovely_choices/config.ru:in `<main>'
	from /home/mary/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
	from /home/mary/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
	from /home/mary/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
	from /home/mary/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/server.rb:299:in `build_app_and_options_from_config'
	from /home/mary/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/server.rb:208:in `app'
	from /home/mary/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands/server.rb:61:in `app'
	from /home/mary/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/server.rb:336:in `wrapped_app'
	from /home/mary/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands/server.rb:139:in `log_to_stdout'
	from /home/mary/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands/server.rb:78:in `start'
	from /home/mary/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:80:in `block in server'
	from /home/mary/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:75:in `tap'
	from /home/mary/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:75:in `server'
	from /home/mary/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/mary/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands.rb:17:in `<top (required)>'
	from /home/mary/src/lovely_choices/bin/rails:8:in `require'
	from /home/mary/src/lovely_choices/bin/rails:8:in `<top (required)>'
	from /home/mary/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/spring-1.4.0/lib/spring/client/rails.rb:28:in `load'
	from /home/mary/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/spring-1.4.0/lib/spring/client/rails.rb:28:in `call'
	from /home/mary/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/spring-1.4.0/lib/spring/client/command.rb:7:in `call'
	from /home/mary/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/spring-1.4.0/lib/spring/client.rb:28:in `run'
	from /home/mary/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/spring-1.4.0/bin/spring:49:in `<top (required)>'
	from /home/mary/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/spring-1.4.0/lib/spring/binstub.rb:11:in `load'
	from /home/mary/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/spring-1.4.0/lib/spring/binstub.rb:11:in `<top (required)>'
	from /home/mary/src/lovely_choices/bin/spring:13:in `require'
	from /home/mary/src/lovely_choices/bin/spring:13:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'
```

db migrate
```
bundle exec rake db:migrate db:seed
warning: parser/current is loading parser/ruby22, which recognizes
warning: 2.2.3-compliant syntax, but you are running 2.2.1.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
rake aborted!
NoMethodError: undefined method `models_with_permission=' for Faalis::Engine:Class
/home/mary/src/lovely_choices/config/initializers/faalis.rb:9:in `block in <top (required)>'
/home/mary/src/lovely_choices/config/initializers/faalis.rb:1:in `<top (required)>'
/home/mary/src/lovely_choices/config/environment.rb:5:in `<top (required)>'
Tasks: TOP => db:migrate => environment
```

**Comment by edelwies** [comment]
Gemfile.lock
GIT
  remote: git://github.com/Yellowen/Faalis.git
  revision: d250a3f0bfe6853c09571a6d6f22bd3b91f10a60
  specs:
    faalis (2.0.0.rc3)
      admin_lte-rails (~> 2.2.0.7)
      coffee-rails
      colorize
      devise (~> 3.5, >= 3.4.0)
      formtastic
      formtastic-bootstrap
      i18n
      jbuilder
      jquery-turbolinks
      kaminari
      model_discovery (~> 0.3.0)
      modernizr-rails
      nprogress-rails
      omniauth
      orm_adapter
      pundit
      rails (~> 4.2, >= 4.2.0)
      rails-assets-sugar (= 1.4.1)
      rails-i18n
      sass-rails
      slim-rails
      sprockets
      turbolinks

GEM
  remote: http://rails-assets.org/
  remote: https://rubygems.org/
  specs:
    actionmailer (4.2.1)
      actionpack (= 4.2.1)
      actionview (= 4.2.1)
      activejob (= 4.2.1)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 1.0, >= 1.0.5)
    actionpack (4.2.1)
      actionview (= 4.2.1)
      activesupport (= 4.2.1)
      rack (~> 1.6)
      rack-test (~> 0.6.2)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.1)
    actionview (4.2.1)
      activesupport (= 4.2.1)
      builder (~> 3.1)
      erubis (~> 2.7.0)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.1)
    activejob (4.2.1)
      activesupport (= 4.2.1)
      globalid (>= 0.3.0)
    activemodel (4.2.1)
      activesupport (= 4.2.1)
      builder (~> 3.1)
    activerecord (4.2.1)
      activemodel (= 4.2.1)
      activesupport (= 4.2.1)
      arel (~> 6.0)
    activerecord-colored_log_subscriber (0.1.0)
      activerecord (>= 3.2, < 5.0)
    activesupport (4.2.1)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    admin_lte-rails (2.2.0.9)
      bootstrap-sass
      bootstrap3-datetimepicker-rails
      chart-js-rails
      font-awesome-rails
      ionicons-rails
      jquery-rails
      jquery-ui-rails
      momentjs-rails
      select2-rails
    annotate (2.6.10)
      activerecord (>= 3.2, <= 4.3)
      rake (~> 10.4)
    arel (6.0.3)
    ast (2.1.0)
    astrolabe (1.3.1)
      parser (~> 2.2)
    autoprefixer-rails (6.0.3)
      execjs
      json
    bcrypt (3.1.10)
    binding_of_caller (0.7.2)
      debug_inspector (>= 0.0.1)
    bootstrap-sass (3.3.5.1)
      autoprefixer-rails (>= 5.0.0.1)
      sass (>= 3.3.0)
    bootstrap3-datetimepicker-rails (4.17.37)
      momentjs-rails (>= 2.8.1)
    builder (3.2.2)
    byebug (6.0.2)
    chart-js-rails (0.0.9)
      railties (> 3.1)
    coderay (1.1.0)
    coffee-rails (4.1.0)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0, < 5.0)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.9.1.1)
    colorize (0.7.7)
    debug_inspector (0.0.2)
    devise (3.5.2)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 3.2.6, < 5)
      responders
      thread_safe (~> 0.1)
      warden (~> 1.2.3)
    erubis (2.7.0)
    execjs (2.6.0)
    font-awesome-rails (4.4.0.0)
      railties (>= 3.2, < 5.0)
    formtastic (3.1.3)
      actionpack (>= 3.2.13)
    formtastic-bootstrap (3.1.1)
      formtastic (>= 3.0)
    globalid (0.3.6)
      activesupport (>= 4.1.0)
    hashie (3.4.2)
    i18n (0.7.0)
    ionicons-rails (2.0.0)
    jbuilder (2.3.2)
      activesupport (>= 3.0.0, < 5)
      multi_json (~> 1.2)
    jquery-rails (4.0.5)
      rails-dom-testing (~> 1.0)
      railties (>= 4.2.0)
      thor (>= 0.14, < 2.0)
    jquery-turbolinks (2.1.0)
      railties (>= 3.1.0)
      turbolinks
    jquery-ui-rails (5.0.5)
      railties (>= 3.2.16)
    json (1.8.3)
    kaminari (0.16.3)
      actionpack (>= 3.0.0)
      activesupport (>= 3.0.0)
    loofah (2.0.3)
      nokogiri (>= 1.5.9)
    mail (2.6.3)
      mime-types (>= 1.16, < 3)
    method_source (0.8.2)
    mime-types (2.6.2)
    mini_portile (0.6.2)
    minitest (5.8.1)
    model_discovery (0.3.7)
      orm_adapter
      railties (~> 4)
    modernizr-rails (2.7.1)
    momentjs-rails (2.10.6)
      railties (>= 3.1)
    multi_json (1.11.2)
    nokogiri (1.6.6.2)
      mini_portile (~> 0.6.0)
    nprogress-rails (0.1.6.7)
    omniauth (1.2.2)
      hashie (>= 1.2, < 4)
      rack (~> 1.0)
    orm_adapter (0.5.0)
    parser (2.2.3.0)
      ast (>= 1.1, < 3.0)
    powerpack (0.1.1)
    pry (0.10.3)
      coderay (~> 1.1.0)
      method_source (~> 0.8.1)
      slop (~> 3.4)
    pry-doc (0.8.0)
      pry (~> 0.9)
      yard (~> 0.8)
    pry-rails (0.3.4)
      pry (>= 0.9.10)
    pundit (1.0.1)
      activesupport (>= 3.0.0)
    quiet_assets (1.1.0)
      railties (>= 3.1, < 5.0)
    rack (1.6.4)
    rack-test (0.6.3)
      rack (>= 1.0)
    rails (4.2.1)
      actionmailer (= 4.2.1)
      actionpack (= 4.2.1)
      actionview (= 4.2.1)
      activejob (= 4.2.1)
      activemodel (= 4.2.1)
      activerecord (= 4.2.1)
      activesupport (= 4.2.1)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.2.1)
      sprockets-rails
    rails-assets-admin-lte (2.3.0)
    rails-assets-bootstrap (3.3.4)
      rails-assets-jquery (>= 1.9.1)
    rails-assets-bootstrap-daterangepicker (2.1.13)
      rails-assets-jquery (>= 1.10)
      rails-assets-moment (>= 2.9.0)
    rails-assets-bootstrap-rtl (3.3.4)
      rails-assets-bootstrap (= 3.3.4)
    rails-assets-jquery (2.1.4)
    rails-assets-jquery-icheck (1.0.2)
      rails-assets-jquery (>= 1.7)
    rails-assets-jquery-knob (1.2.11)
      rails-assets-jquery (>= 1.7.0)
    rails-assets-jquery-sparkline (2.1.3)
    rails-assets-moment (2.10.6)
    rails-assets-sugar (1.4.1)
    rails-deprecated_sanitizer (1.0.3)
      activesupport (>= 4.2.0.alpha)
    rails-dom-testing (1.0.7)
      activesupport (>= 4.2.0.beta, < 5.0)
      nokogiri (~> 1.6.0)
      rails-deprecated_sanitizer (>= 1.0.1)
    rails-html-sanitizer (1.0.2)
      loofah (~> 2.0)
    rails-i18n (4.0.5)
      i18n (~> 0.6)
      railties (~> 4.0)
    railties (4.2.1)
      actionpack (= 4.2.1)
      activesupport (= 4.2.1)
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rainbow (2.0.0)
    rake (10.4.2)
    rb-readline (0.5.3)
    rdoc (4.2.0)
    responders (2.1.0)
      railties (>= 4.2.0, < 5)
    rubocop (0.34.2)
      astrolabe (~> 1.3)
      parser (>= 2.2.2.5, < 3.0)
      powerpack (~> 0.1)
      rainbow (>= 1.99.1, < 3.0)
      ruby-progressbar (~> 1.4)
    ruby-progressbar (1.7.5)
    sass (3.4.19)
    sass-rails (5.0.4)
      railties (>= 4.0.0, < 5.0)
      sass (~> 3.1)
      sprockets (>= 2.8, < 4.0)
      sprockets-rails (>= 2.0, < 4.0)
      tilt (>= 1.1, < 3)
    sdoc (0.4.1)
      json (~> 1.7, >= 1.7.7)
      rdoc (~> 4.0)
    select2-rails (4.0.0)
      thor (~> 0.14)
    slim (3.0.6)
      temple (~> 0.7.3)
      tilt (>= 1.3.3, < 2.1)
    slim-rails (3.0.1)
      actionmailer (>= 3.1, < 5.0)
      actionpack (>= 3.1, < 5.0)
      activesupport (>= 3.1, < 5.0)
      railties (>= 3.1, < 5.0)
      slim (~> 3.0)
    slop (3.6.0)
    spring (1.4.0)
    sprockets (3.4.0)
      rack (> 1, < 3)
    sprockets-rails (2.3.3)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      sprockets (>= 2.8, < 4.0)
    sqlite3 (1.3.11)
    temple (0.7.6)
    thor (0.19.1)
    thread_safe (0.3.5)
    tilt (2.0.1)
    turbolinks (2.5.3)
      coffee-rails
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    uglifier (2.7.2)
      execjs (>= 0.3.0)
      json (>= 1.8.0)
    warden (1.2.3)
      rack (>= 1.0)
    web-console (2.2.1)
      activemodel (>= 4.0)
      binding_of_caller (>= 0.7.2)
      railties (>= 4.0)
      sprockets-rails (>= 2.0, < 4.0)
    yard (0.8.7.6)

PLATFORMS
  ruby

DEPENDENCIES
  activerecord-colored_log_subscriber
  admin_lte-rails
  annotate
  autoprefixer-rails
  bootstrap3-datetimepicker-rails
  byebug
  coffee-rails (~> 4.1.0)
  faalis!
  jbuilder (~> 2.0)
  jquery-rails
  jquery-turbolinks
  method_source
  minitest
  momentjs-rails
  pry-doc
  pry-rails
  quiet_assets
  rails (= 4.2.1)
  rails-assets-admin-lte
  rails-assets-bootstrap-daterangepicker
  rails-assets-bootstrap-rtl
  rails-assets-jquery-icheck
  rails-assets-jquery-knob
  rails-assets-jquery-sparkline
  rails-assets-sugar
  rails-i18n
  rb-readline
  rubocop
  sass-rails (~> 5.0)
  sdoc (~> 0.4.0)
  spring
  sqlite3
  turbolinks
  uglifier (>= 1.3.0)
  web-console (~> 2.0)

**Comment by lxsameer** [comment]
thanks for reporting

**Comment by lxsameer** [comment]
It seems that you're upgrading from an old version of **Faalis**. Please remove the `model_with_permissions` from `config/initializers/faalis.rb` and rerun your server
