### ISSUE TITLE
Error installing faalis

### ISSUE THREAD

**Issue by purias** [Yellowen/Faalis#65]
I get this error when doing "rails g faalis:install" : 
https://gist.github.com/anonymous/19b4ec02119fd54607a3

my gemfile is: 
https://gist.github.com/purias/0b4f9f85966f91e7664f

**Comment by lxsameer** [comment]
@purias can you give me your `config/routes.rb` please ?

**Comment by purias** [comment]
https://gist.github.com/purias/a802d73429d507b8a098

**Comment by lxsameer** [comment]
@purias confirmed, It will be fixed in couple of minutes, but make sure to use `faalis` version `2.0.1` gem and add faalis related gems to the end of your `Gemfile`
