### ISSUE TITLE
ran a linter (rubocop) across project

### ISSUE THREAD

**Issue by Bobby-H** [Yellowen/Faalis#67]
```
198 files inspected, 1573 offenses detected
```

**Comment by lxsameer** [comment]
@Bobby-H thanks for reporting. I'm aware of that, but they are mostly related to legacy code and coding style issues. Our main concern is to fix issues reports by code climate .

**Comment by Bobby-H** [comment]
```
198 files inspected, 2253 offenses detected, 1604 offenses corrected
```
At a glance most 'corrections' seem to be purely cosmetic. Oh you're fast, haha! Yeah, code climate is certainly more worthy of your time. Faalis seems great!

**Comment by lxsameer** [comment]
@Bobby-H thanks, Also we would appreciate any contribution

**Comment by Bobby-H** [comment]
Heard loud and clear; just Starred Faalis and will contribute anything that
comes to me.

**Comment by lxsameer** [comment]
Awesome. :+1:

**Comment by yottanami** [comment]
:+1:
